_material_indigo_800 = "#233593"

blue_and_cyan = {
    "button-border-radius": "2px",
    "button-contained-background-color": _material_indigo_800,
    "button-contained-border-color": _material_indigo_800,
    "button-contained-color": "#ffffff",
    "button-contained-background-color-focus": "rgba(0, 229, 255, 0.96)",
    "button-contained-border-color-focus": "#aaaaaa",
    "button-contained-color-focus": "#001064",
    "button-contained-background-color-hover": "rgba(0, 229, 255, 0.48)",
    "button-contained-border-color-hover": "#aaaaaa",
    "button-contained-color-hover": "#001064",
    "button-contained-background-color-pressed": "rgba(0, 229, 255, 0.32)",
    "button-contained-border-color-pressed": "#aaaaaa",
    "button-contained-color-pressed": "#001064",
    "button-contained-background-color-disabled": "#cccccc",
    "button-contained-border-color-disabled": "#cccccc",
    "button-contained-color-disabled": "#838383",
    "button-outlined-border-color": "#aaaaaa",
    "button-outlined-color": "#001064",
    "button-outlined-background-color-focus": "rgba(0, 229, 255, 0.48)",
    "button-outlined-background-color-hover": "rgba(0, 229, 255, 0.96)",
    "button-outlined-background-color-pressed": "rgba(0, 229, 255, 0.32)",
    "button-outlined-border-color-disabled": "#cccccc",
    "button-outlined-color-disabled": "#838383",
    "button-text-border-color": "transparent",
    "button-text-color": "#001064",
    "button-text-background-color-focus": "rgba(0, 229, 255, 0.48)",
    "button-text-color-focus": "#000000",
    "button-text-background-color-hover": "rgba(0, 229, 255, 0.96)",
    "button-text-color-hover": "#000000",
    "button-text-background-color-pressed": "rgba(0, 229, 255, 0.32)",
    "button-text-color-pressed": "#000000",
    "button-text-color-disabled": "#838383",
}


_material_example_purple = "#6200ee"

material_purple = {
    "button-border-radius": "4px",
    "button-contained-background-color": _material_example_purple,
    "button-contained-border-color":  _material_example_purple,
    "button-contained-color": "#ffffff",
    "button-contained-background-color-focus": "#873df2",
    "button-contained-border-color-focus": "#873df2",
    "button-contained-color-focus": "white",
    "button-contained-background-color-hover": "#6e14ef",
    "button-contained-border-color-hover": "#6e14ef",
    "button-contained-color-hover": "#ffffff",
    "button-contained-background-color-pressed": "#9452f3",
    "button-contained-border-color-pressed": "#9452f3",
    "button-contained-color-pressed": "#ffffff",
    "button-contained-background-color-disabled": "#cccccc",
    "button-contained-border-color-disabled": "#cccccc",
    "button-contained-color-disabled": "#838383",
    "button-outlined-border-color": "#aaaaaa",
    "button-outlined-color": _material_example_purple,
    "button-outlined-background-color-focus": "rgba(98, 0, 238, 0.12)",
    "button-outlined-background-color-hover": "rgba(98, 0, 238, 0.08)",
    "button-outlined-background-color-pressed": "rgba(98, 0, 238, 0.24)",
    "button-outlined-border-color-disabled": "#cccccc",
    "button-outlined-color-disabled": "#838383",
    "button-text-border-color": "transparent",
    "button-text-color": _material_example_purple,
    "button-text-background-color-focus": "rgba(98, 0, 238, 0.12)",
    "button-text-color-focus": "#000000",
    "button-text-background-color-hover": "rgba(98, 0, 238, 0.08)",
    "button-text-color-hover": "#000000",
    "button-text-background-color-pressed": "rgba(98, 0, 238, 0.24)",
    "button-text-color-pressed": "#000000",
    "button-text-color-disabled": "#838383",
}
